version: '3.8'

services:
  backend:
    build: .
    container_name: archie-backend
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://homeassistant_user:homeassistant_password@host.docker.internal:5432/homeassistant_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: archie-redis
    ports:
      - "8004:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:

networks:
  shared_network:
    external: true
