"""Update LllmTrace model structure with token details

Revision ID: d3bd9f810a99
Revises: a4ae314ae9b0
Create Date: 2025-10-02 00:29:37.586662

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d3bd9f810a99"
down_revision: str | Sequence[str] | None = "a4ae314ae9b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
